<!DOCTYPE html>
<html class>
    <head>
        <!-- METADATOS -->
        <meta charset="utf-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1">
<!-- Las 3 metaetiquetas anteriores *deben* aparecer primero en el encabezado; cualquier otro contenido principal debe venir *después* de estas etiquetas -->		
		

        <!--familia-de-fuentes-->
		<link href="https://fonts.googleapis.com/css?family=Playfair+Display:400,400i,700,700i,900,900i" rel="stylesheet">
		
		<link href="https://fonts.googleapis.com/css?family=Poppins:100,200,300,400,500,600,700,800,900" rel="stylesheet">
		
		<link href="https://fonts.googleapis.com/css?family=Lato:100,300,400,700,900" rel="stylesheet">
		
        <!-- TÍTULO DEL SITIO -->
        <title>PRACTICA INTEGRADOR</title>

        <!-- para título img -->
		<link rel="shortcut icon" type="image/icon" href="assets/images/logo/favicon.png"/>
       
        <!--font-awesome.min.css-->
        <link rel="stylesheet" href="assets/css/font-awesome.min.css">
		
		<!--linea icon css-->
		<link rel="stylesheet" href="https://cdn.linearicons.com/free/1.0.0/icon-font.min.css">
		
		<!--animacio.css-->
        <link rel="stylesheet" href="assets/css/animate.css">
		
		
        <link rel="stylesheet" href="assets/css/hover-min.css">
        <link rel="stylesheet" href="assets/css/magnific-popup.css">
        <link rel="stylesheet" href="assets/css/owl.carousel.min.css">
		<link href="assets/css/owl.theme.default.min.css" rel="stylesheet"/>
        <link rel="stylesheet" href="assets/css/bootstrap.min.css">
		<link href="assets/css/bootsnav.css" rel="stylesheet"/>	
        <link rel="stylesheet" href="assets/css/style.css">
        <link rel="stylesheet" href="assets/css/responsive.css">

    </head>
	
	<body>
	
		<!--inicio del header -->
		<section class="header">
			<div class="container">	
				<div class="header-left">
					<ul class="pull-left">
						<li>
							<h5>Numero</h5>

							<a href="#">
								 7292807596
							</a>
						</li><!--/li-->
						<li>
							<h5>Correo Electronico</h5>
							<a href="#">
								al222110706@mail.com
							</a>
						</li><!--/li-->
					</ul><!--/ul-->
				</div>
				<div class="header-right pull-right">
					<ul>
						
						
						
						<!-- pequeño modal -->
						<h2><a href="admin/login.php" >INICIO SESION</a></h2> 
							</li>
					</ul>
				</div>
			</div>	

		</section>	
<!--fin del encabezado-->
		
		<!--menu inicio-->
		<section id="menu">
			<div class="container">
				<div class="menubar">
					<nav class="navbar navbar-default">
					
						<!-- Marca y alternar se agrupan para una mejor visualización móvil -->
						<div class="navbar-header">
							<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
								<span class="sr-only">Navegación de palanca</span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
								<span class="icon-bar"></span>
							</button>
							

						<!-- Recopile los enlaces de navegación, formularios y otro contenido para alternar -->
						<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
							<ul class="nav navbar-nav navbar-right">
								<li class="active"><a href="index.php">INICIO</a></li>
								<li><a href="servicio.php">SERVICIO</a></li>
								<li><a href="Calcula Tu Desperdicio.pht">CALCULA TU DESPERDICIO</a></li>
								<li><a href="ORGANIZA TU NEVERA.php">ORGANIZA TU NEVERA  </a></li>
								<li><a href="tienda.php">CADUCIDAD Y CONSUMO</a></li>
								<li><a href="index.php">SOPORTE</a></li>

								<li class="search">
									<form action="">
										<input type="text" name="search" placeholder="Search....">
										<a href="#">
											<span class="lnr lnr-magnifier"></span>
										</a>
									</form>
								</li>
							</ul><!-- / ul -->
						</div><!-- /.navbar-collapse -->
					</nav><!--/nav -->
				</div><!--/.menubar -->
			</div><!-- /.container -->

		</section><!--/#menu-->
		<!--menu end-->
		
		<!-- encabezado-slider-area inicio -->
		<section class="header-slider-area">
			<div id="carousel-example-generic" class="carousel slide carousel-fade" data-ride="carousel">
			
			  <!-- Indicadores -->
				<ol class="carousel-indicators">
					<li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
					<li data-target="#carousel-example-generic" data-slide-to="1"></li>
				</ol>

				<!-- Envoltorio para diapositivas -->
				<div class="carousel-inner" role="listbox">
					<div class="item active">
						<div class="single-slide-item slide-1">
							<div class="container">
								<div class="row">
									<div class="col-sm-12">
										<div class="single-slide-item-content">
											<h2>Consulte sus productos <br> Con nosotros</h2>
											<p>
												Somos un grupo de emprendedores para la solución de su negocio, que está lista para enfrentar el desafío y eliminar los problemas. 
											</p>
											<button type="button" class="slide-btn">
												Iniciamos
											</button>
											<button type="button"  class="slide-btn">
												explora más
											</button>
											
										</div>
									</div>
								</div>
							</div>
						</div>
					</div>

					</Section>
					

				<!-- Controles -->
				<a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
					<span class="lnr lnr-chevron-left"></span>
				</a>
				<a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
					<span class="lnr lnr-chevron-right"></span>
				</a>
			</div>

		</section>
		
		
		<!--comenzamos -->
		<section  class="we-do">
			<div class="container">
				<div class="we-do-details">
					<div class="section-header text-center">
						<h2>que hacemos</h2>
						<p>
							OFRECEMOS NUESTRA PAGINA WEB PARA SUS ALIMENTOS  
						</p>
					
		<!--comienzan las estadísticas-->
		<section  class="statistics">
			<div class="container">
				<div class="statistics-counter "> 
					<div class="col-md-3 col-sm-6">
						<div class="single-ststistics-box">
							<div class="statistics-img">
								<img src="assets/images/counter/counter1.png" alt="counter-icon" />
							</div>
							<div class="statistics-content">
								<div class="counter">2556</div>
								<h3>trabajo</h3>
							</div>
						</div>
					</div>
					<div class="col-md-3 col-sm-6">
						<div class="single-ststistics-box">
							<div class="statistics-img">
								<img src="assets/images/counter/counter2.png" alt="counter-icon" />
							</div>
							<div class="statistics-content">
								<div class="counter">326</div>
								<h3>proytecto final </h3>
							</div>
						</div>
					</div>
					<div class="col-md-3 col-sm-6">
						<div class="single-ststistics-box">
							<div class="statistics-img">
								<img src="assets/images/counter/counter3.png" alt="counter-icon" />
							</div><!--/.statistics-img-->
							<div class="statistics-content">
								<div class="counter">1526</div>
								<h3>taza de café</h3>
							</div><!--/.statistics-content-->
						</div><!--/.single-ststistics-box-->
					</div><!--/.col-->
					<div class="col-md-3 col-sm-6">
						<div class="single-ststistics-box">
							<div class="statistics-img">
								<img src="assets/images/counter/counter4.png" alt="counter-icon" />
							</div><!--/.statistics-img-->
							<div class="statistics-content">
								<div class="counter">856</div>
								<h3>cliente satisfecho</h3>
							</div>
						</div>
					</div>
				</div>
			</div>
		</section><!--/.statistics-->
			
		<!-- nuevo-proyecto  -->
				<section  id="new-project" class="new-project">
					<div class="container">
						<div class="new-project-details">
							<div class="row">
								<div class="col-md-10 col-sm-8">
									<div class="single-new-project">
										<h3>
											¿Quieres iniciar un nuevo proyecto con nosotros? ¡Empecemos!
										</h3>
									</div><!-- /.single-new-project-->	
								</div><!-- /.col-->	
								<div class="col-md-2 col-sm-4">
									<div class="single-new-project">
										<a href="#" class="slide-btn">
											INICIAMOS
										</a>
									</div><!-- /.single-new-project-->	
								</div><!-- /.col-->	
							</div><!-- /.row-->	
						</div><!-- /.new-project-details-->	
					</div><!-- /.container-->
			
			
				</section>
				<!-- new-project end -->
		
		
				<!--comenzamos -->
				<section  class="we-do"> <!--separar-->
				<section><div class="container">
					<div class="new-project-details">
						<div class="row">
								<div class="single-new-project">
									<h3>
                                     <div>
										<div>
											<div>
						<h2>Que Puedes Hacer Tu</h2>
						</section>
                         <section><p>
							¿Te has preguntado alguna vez cuánto desperdicias?
						 Seguramente algo más de lo que imaginas… y no es que tengamos ganas de exagerar.
							
						</p></section>	</div>
					</div>
				</div>
			</div>


				<section>
					<div class= "new-project">
						<div class="row"> <!--color blanco-->
							<div class="single-new-project"><!--color blanco-->
								<h3><!--color blanco-->
						<div>
						   <div>
						   <div>
							 <h2>¡Te Proponemos Una Serie De Herramientas Para Un Consumo Más Consciente!
							 </h2>
						   
							   
							 </div>
							</div>			 
						 </div>
		   
				   </section> <section>
						<div class="about-history">
							<div class="container">
							<div class="about-history-content">
						
								<div class="row">

					        <div class= "new-project">
							
								<div class="col-md-2 col-sm-6">
									<div class="timeline timeline-ml-1">
				                <img src="assets/images/banner/banner3.png" alt="counter-icon" />
									</div>
								</div>
						
								
				                  <div class="single-about-history">
									<div class="about-history-txt">
										
								   <h1>¡Prueba la calculadora! </h1>
								   
								  </div>
								  <div class="single-new-project">
								
									<p>¡Seguro que no te imaginas cuánto desperdicias! 
					                     Te invitamos a que midas cuánto tiras 
				                    	a la basura en un sólo día.
									</p> 
								  </div>
									<div class="single-new-project">
										<a href="#" class="slide-btn">
											INICIAMOS
										</a>	
									</section>
									<div class="about-history">
					<div class="container">
					<div class="about-history-content">
				
						<div class="row">

					<div class= "new-project">
					
						<div class="col-md-2 col-sm-3">
							<div class="timeline timeline-ml-1">
						<img src="assets/images/banner/banner4.png" alt="counter-icon" />
							</div>
						</div>
				
						
						  <div class="single-about-history">
							<div class="about-history-txt">
								
						   <h1>Caducidad… Consumo preferente… ¿Cuál es cual?
						</h1>
						   
						  </div>
						  <div class="single-new-project">
							
							<p>¡Confundir fecha de caducidad y de consumo preferente es muy habitual y puede ser la causa de que tiremos a la basura alimentos perfectamente válidos para el consumo.
							</p> 
						  </div>
							<div class="single-new-project">
								<a href="#" class="slide-btn">
									DIFERENCIAS
								</a>	
							</section>
							
						  </div>
						 </div>			 
					  </div>
		
				</section>
	</div>

	<!--hm-footer start-->
	<section>
	<div class="hm-footer">
		<div class="container">
			<div class="hm-footer-details">
				<div class="row">
					<div class="col-md-4 col-sm-6 col-xs-12">
						<div class="hm-footer-widget">
							<div class="hm-foot-title ">
								<div class="logo">
									<a href="index.html">
										
									</a>
								</div><!-- /.logo-->
							</div><!--/.hm-foot-title-->
							<div class="hm-foot-para">
								<p>
									
								</p>
							</div><!--/.hm-foot-para-->
							<div class="hm-foot-icon">
								<ul>
									<li><a href="#"><i class="fa fa-facebook" aria-hidden="true"></i></a></li><!--/li-->
									<li><a href="#"><i class="fa fa-twitter" aria-hidden="true"></i></a></li><!--/li-->
								</ul><!--/ul-->
							</div><!--/.hm-foot-icon-->
						</div><!--/.hm-footer-widget-->
					</div><!--/.col-->
					<div class=" col-md-2 col-sm-6 col-xs-12">
						<div class="hm-footer-widget">
							<div class="hm-foot-title">
								<h4>Enlaces</h4>
							</div><!--/.hm-foot-title-->
							<div class="footer-menu ">	  
								<ul class="">
									<li><a href="index.PHP" >Inicio</a></li>
									<li><a href="about.PHP">Punto de venta</a></li>
									<li><a href="services.PHP">Servicio</a></li>
									<li><a href="portfolio.PHP">Casos de éxito</a></li>
									<li><a href="blog.PHP">Tienda</a></li>
									<li><a href="blog.PHP">Soporte</a></li>
									<li><a href="contact.PHP">Contacto</a></li> 
								</ul>
							</div><!-- /.footer-menu-->
						</div><!--/.hm-footer-widget-->
					</div><!--/.col-->
					<div class=" col-md-3 col-sm-6 col-xs-12">
						<div class="hm-footer-widget">
							<div class="hm-foot-title">
								<h4>Acerca de la empresa</h4>
							</div><!--/.hm-foot-title-->
							<div class="hm-para-news">
								<a href="blog_single.html">
									Pros y contras de crear tu propio negocio
								</a>
								<span>12 June 2022</span>
							</div><!--/.hm-para-news-->
							<div class="footer-line">
								<div class="border-bottom"></div>
							
							</div><!--/.hm-para-news-->
						</div><!--/.hm-footer-widget-->
					</div><!--/.col-->
					<div class=" col-md-3 col-sm-6  col-xs-12">
						<div class="hm-footer-widget">
							<div class="hm-foot-title">
								<h4> Nuestra información</h4>
							</div><!--/.hm-foot-title-->
							<div class="hm-foot-para">
								<p class="para-news">
									Suscribete para recibir noticias acerca de nuestras ofertas
								</p>
							</div><!--/.hm-foot-para-->
							<div class="hm-foot-email">
								<div class="foot-email-box">
									<input type="text" class="form-control" placeholder="Email Address">
								</div><!--/.foot-email-box-->
								<div class="foot-email-subscribe">
									<button type="button" >vamos</button>
								</div><!--/.foot-email-icon-->
							</div><!--/.hm-foot-email-->
						</div><!--/.hm-footer-widget-->
					</div><!--/.col-->
				</div><!--/.row-->
			</div><!--/.hm-footer-details-->
		</div><!--/.container-->
	</div>
	</section><!--/.hm-footer-details-->
	<!--hm-footer end-->
	
	<!-- footer-copyright start -->
	<footer class="footer-copyright">
		<div class="container">
			<div class="row">
				<div class="col-sm-7">
					<div class="foot-copyright pull-left">
						<p>
							&copy; All Rights Reserve
							 <a href="https://www.themesine.com">TechnoFood</a>
						</p>
					</div><!--/.foot-copyright-->
				</div><!--/.col-->
				<div class="col-sm-5">
					<div class="foot-menu pull-right
					">	  
						<ul>
							<li ><a href="#">legal</a></li>
							<li ><a href="#">sitema</a></li>
							<li ><a href="#">politicas de privacidad</a></li>
						</ul>
					</div><!-- /.foot-menu-->
				</div><!--/.col-->
			</div><!--/.row-->
			<div id="scroll-Top">
				<i class="fa fa-angle-double-up return-to-top" id="scroll-top" data-toggle="tooltip" data-placement="top" title="" data-original-title="Back to Top" aria-hidden="true"></i>
			</div><!--/.scroll-Top-->
		</div><!-- /.container-->

	</footer><!-- /.footer-copyright-->
	<!-- footer-copyright end -->



	<!-- jaquery link -->

	<script src="assets/js/jquery.js"></script>
	<!-- Include all compiled plugins (below), or include individual files as needed -->
	
	<!--modernizr.min.js-->
	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/modernizr/2.8.3/modernizr.min.js"></script>
	
	
	<!--bootstrap.min.js-->
	<script type="text/javascript" src="assets/js/bootstrap.min.js"></script>
	
	<!-- bootsnav js -->
	<script src="assets/js/bootsnav.js"></script>
	
	<!-- for manu -->
	<script src="assets/js/jquery.hc-sticky.min.js" type="text/javascript"></script>

	
	<!-- vedio player js -->
	<script src="assets/js/jquery.magnific-popup.min.js"></script>


	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/jquery-easing/1.4.1/jquery.easing.min.js"></script>

	<!--owl.carousel.js-->
	<script type="text/javascript" src="assets/js/owl.carousel.min.js"></script>
	
	<!-- counter js -->
	<script src="assets/js/jquery.counterup.min.js"></script>
	<script src="assets/js/waypoints.min.js"></script>
	
	<!--Custom JS-->
	<script type="text/javascript" src="assets/js/jak-menusearch.js"></script>
	<script type="text/javascript" src="assets/js/custom.js"></script>
	

</body>

</html>


